### ISSUE TITLE
defmt issue when crate name starts with number

### ISSUE THREAD

**Issue by jessetp** [knurling-rs/knurling-session-20q4#30]
defmt does not work when the crate name starts with a number (e.g. `01_hello_extended.rs`). I used the app template generator as suggested in the Knurling-session-20q4.

Dependencies used in `Cargo.toml`:

```toml
[dependencies]
nrf52840-hal = "0.15.1"
embedded-hal = "0.2.7"
cortex-m = "0.7.6"
cortex-m-rt = "0.7.1"
defmt = "0.3.2"
defmt-rtt = "0.3.2"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
nb = "1.0.0"
crc_all = "0.2.2"
```
